### ISSUE TITLE
Зарегистрировать домен

### ISSUE THREAD

**Issue by roll** [krogh7/arunalab.ru#1]
arunalab.ru

**Comment by roll** [comment]
nic.ru

**Comment by L1SS** [comment]
Hello it is Andrey

**Comment by L1SS** [comment]
Please. Help me? i don not understand how to create domen host. i sent you screenshot by e-mail!

**Comment by roll** [comment]
Do you speak russian?

https://gitter.im/krogh7/arunalab.ru

**Comment by L1SS** [comment]
Is it joke?

**Comment by roll** [comment]
No. I'm pretty serious. It's essential for the project. Please close this issue when you're done the domain registration using "Close issue" button at github below comment area or moving it to the "Done" column at waffle - https://waffle.io/krogh7/arunalab.ru

**Comment by krogh7** [comment]
Зарегистрировано.
