### ISSUE TITLE
Закрыть задачи в Мегаплане

### ISSUE THREAD

**Issue by krogh7** [krogh7/arunalab.ru#13]
Все задачи, связанные с сайтом перенести из Мегаплана в Вафлю. При этом рассказать нам всем, в чем суть разделения проекта на подпроекты. И в чем прелесть использования новых инструментов. А также расписать (или рассказать в скайп конференции), как настроить эти механизмы.

**Comment by roll** [comment]
Я сделал презентацию

https://gitter.im/krogh7/arunalab.ru

**Comment by krogh7** [comment]
Загнать в мегаплан можешь как задачу?   все эти ссылки безумные теряются в потоках твоих речей в том общем чатике

**Comment by roll** [comment]
Ну вообще потоки я вылилвал в нашу личную переписку) В общем чате как раз на первом экране сейчас все собрано.

**Comment by roll** [comment]
важно? срочно? кто установил эти ярлыки? getting things done - не?

**Comment by krogh7** [comment]
Я установил)

**Comment by krogh7** [comment]
Задача почти готова (остается только Андрею зарегистрировать домен)

**Comment by roll** [comment]
У меня еще вот это висит - https://arunalab.megaplan.ru/task/1000023/card/?fromList=1000023

**Comment by krogh7** [comment]
Да, не закрываю ее - жду когда Андрей прочитает. 

Fofanov
fofanov.dima@gmail.com

**Comment by krogh7** [comment]
Андрюх, ознакомся с ссылками  под  https://arunalab.megaplan.ru/task/1000023/card/?fromList=1000023 в Мегаплане  и закрываем

**Comment by L1SS** [comment]
OK
