### ISSUE TITLE
Выбрать дизайн для сайта

### ISSUE THREAD

**Issue by roll** [krogh7/arunalab.ru#2]
http://www.bootstrapzero.com/bootstrap-templates
http://startbootstrap.com/
https://wrapbootstrap.com/

http://www.blacktie.co/demo/pratt/
http://shapebootstrap.net/demo/html/corlate/
http://www.scoopthemes.com/templates/Oleose/Freeze/
http://www.blacktie.co/demo/flatty/
http://www.bootply.com/render/129806

**Comment by roll** [comment]
Оль, пиши о своих мыслях по этому поводу сюда в комментарии и в чат п-та.

**Comment by Olguitochka** [comment]
Из уже предложенных вариантов мне понравился вот этот: http://razonartificial.com/themes/reason/v1.4.3/
Такой вариант довольно понятный. Думаю можно его взять за основу.

**Comment by roll** [comment]
Мне тоже нравится - но ты там наращивай свои навыки bootstrap - нам придется разбираться в том, как этот шаблон работает

**Comment by roll** [comment]
@krogh7 - https://wrapbootstrap.com/theme/artificial-reason-responsive-full-pack-WB0307B17 - 16$

**Comment by L1SS** [comment]
Утверждаю, Диман оплачивай!

**Comment by krogh7** [comment]
купил

**Comment by krogh7** [comment]
закачивается

**Comment by krogh7** [comment]
хей, скачалась тема. куда ее выкладывать? тут не прикрепляется.

**Comment by krogh7** [comment]
все. отправил.

**Comment by krogh7** [comment]
принимайте работу

**Comment by L1SS** [comment]
Куда отправил?

**Comment by krogh7** [comment]
Вот сюда:
https://www.dropbox.com/s/u65lbxn3zx95e2z/artificial-reason-1.4.3.zip?dl=0
