### ISSUE TITLE
Перевести разработку сайта на github, waffle и gitter

### ISSUE THREAD

**Issue by roll** [krogh7/arunalab.ru#4]
https://waffle.io/krogh7/arunalab.ru

- [x] зарегистрировать олю на гитхабе и дать ей доступ к репозиторию
- [x] разобраться как работать с задачами на гитхабе/вафле
- [x] разобраться как работает канбан-доска (наконец, finally)

**Comment by roll** [comment]
тест, задача выполнена, перемещаю ее на контроль и переатачиваю на менеджера, чтобы он проверил и переместил в готово

**Comment by L1SS** [comment]
Проверил!
