### ISSUE TITLE
Перерегистрировать хостинг на диму

### ISSUE THREAD

**Issue by roll** [krogh7/arunalab.ru#6]

**Comment by krogh7** [comment]
зачем на меня 

Fofanov
fofanov.dima@gmail.com

**Comment by roll** [comment]
А на кого еще? Тем более интеграция работает только если у репозитория и хостинга один владелец.

**Comment by krogh7** [comment]
пусть Андрюха будет

Fofanov
fofanov.dima@gmail.com

**Comment by roll** [comment]
А ты почему не можешь? С большой долей вероятности там понадобится иногда управлять им из командной строки и т.д. Это не домен - зарегистрировал и забыл.

**Comment by roll** [comment]
Дим, пришли мне городской телефон (желательно) и время, когда мне тебе позвонить - мне надо с тобой серьезно поговорить :sunglasses: :gun:

**Comment by krogh7** [comment]
Городской у меня будет только на выходных (пт-сб-вс) -  +7 495 412 87 86 
В остальное время - один из моих мобильных. 
Скайп не катит? 

Fofanov
fofanov.dima@gmail.com

**Comment by roll** [comment]
Ну катит естественно, я же со скайпа буду звонить.

**Comment by krogh7** [comment]
По тем мотивам, что я параллельно двигаю эту тему через институт океанологии, но там  я со стороны науки. 
А аруналаб - коммерческий проект (во всяком случае большая ее часть).  
АкадЭмикам будет удобнее заключать договора с Андрюхой, нежели со мной.  Политес короче. 
 
Fofanov
fofanov.dima@gmail.com

**Comment by krogh7** [comment]
fofanov777 

Fofanov
fofanov.dima@gmail.com

**Comment by roll** [comment]
Кто владелец хостинга и т.п. это приватная информация, тем более легко изменяемая со временем. Изначально с тобой это будет гораздо легче настроить (хех, ну я надеюсь точнее).

**Comment by krogh7** [comment]
Выпишите мне доверенность)

Fofanov
fofanov.dima@gmail.com

**Comment by roll** [comment]
Блин бизнес по схеме Олега Навального получается)))
